### ISSUE TITLE
Using variable syntax

### ISSUE THREAD

**Issue by dominijk** [iqmo-org/magic_duckdb#16]
Many thanks for all the work on this. 

With duckdb 0.7.1 and magic_duckdb 0.1.25 I could previously use the syntax:

```python
some_sql_query = f''' min(thing) , max(thing) , mean(thing) ''''

%%sql -r
from mytable
select thingname, 
{some_sql_query}
```

When i try this with duckdb>=0.9.0 and magic-duckdb>=0.1.26 i get `UsageError: unrecognized arguments: -r` . If i roll back to magic-duckdb==0.1.25 the syntax works again. Is that a bug?

**Comment by paultiq** [comment]
Sorry for slow response and inconvenience... that -r only lasted one minor release: it was replaced with -j & -p, which are a bit more standard.

In https://github.com/iqmo-org/magic_duckdb/issues/4, for 0.1.26, switched to use -j (jinja expansion) and -p (parameter passing), and removed -r.

Check out https://github.com/iqmo-org/magic_duckdb/blob/main/notebooks/parameters.ipynb for examples.
