### ISSUE TITLE
how to use unsigned plugin?

### ISSUE THREAD

**Issue by Hank-Yan** [iqmo-org/magic_duckdb#19]
magic_duckdb is a great project. The execution speed of jupytersql is too slow, and I think everyone hates that.
However, I encountered a problem in my use. For some inevitable reason, I need to load an unsigned plugin. This is how I wrote it in Python,

```python
conn = duckdb.connect(config={"allow_unsigned_extensions": "true"})  
conn.sql("load spatial")  
  
conn.sql("""  
SELECT ST_AsText(ST_Boundary(ST_GeomFromText('POLYGON((1 1,0 0, -1 1, 1 1))')));  
""")
```

Among them, config={"allow_unsigned_extensions": "true"} is indispensable. But I want to know how to pass this conn to magic_duckdb. I have tried many ways, but it doesn't seem to work.  

please help me..

**Comment by paultiq** [comment]
You can set the dql connection with `%dql -co con`

For instance:
```py
import duckdb
conn = duckdb.connect(config={"allow_unsigned_extensions": "true"})  
conn.sql("load spatial")

# Set the magic_duckdb connection globally
%dql -co conn   
```
```sql
%%dql
SELECT ST_AsText(ST_Boundary(ST_GeomFromText('POLYGON((1 1,0 0, -1 1, 1 1))')));  
```

Alternatively, if you don't want to set it as a global, you can pass it per cell. In this case, the conn is only used for this single cell:
```sql
%%dql -co conn
SELECT ST_AsText(ST_Boundary(ST_GeomFromText('POLYGON((1 1,0 0, -1 1, 1 1))')));  
```

And, for completeness, in a line magic:
```py
import duckdb
conn = duckdb.connect(config={"allow_unsigned_extensions": "true"})  
conn.sql("load spatial")

%dql -co conn SELECT ST_AsText(ST_Boundary(ST_GeomFromText('POLYGON((1 1,0 0, -1 1, 1 1))')));  
```
