### ISSUE TITLE
print(df.to_markdown(index=False))

### ISSUE THREAD

**Issue by paultiq** [iqmo-org/magic_duckdb#20]
I was going to create a similar request but to have the output displayed as Markdown. As a temporary workaround I'm storing the dataframe into a variable and then using the `print(df.to_markdown(index=False))` which gives me the desired output to copy into to a markdown cell. 

![image](https://github.com/iqmo-org/magic_duckdb/assets/5430744/81b4baeb-7669-467a-847d-8858511a4702)

Rendered in the markdown: 
![image](https://github.com/iqmo-org/magic_duckdb/assets/5430744/59685218-f88b-4576-8314-987f25eda0a0)

If I don't include the `print` it the output can't be directly copied into the cell.
![image](https://github.com/iqmo-org/magic_duckdb/assets/5430744/c58fdeae-122f-49a3-b390-eabe84c3cb35)

_Originally posted by @dmcmurchy in https://github.com/iqmo-org/magic_duckdb/issues/18#issuecomment-1942912196_

**Comment by paultiq** [comment]
Yup, I can add a df_markdown or something mode. 

Curious why you use this, is this to copy/paste elsewhere? Or are you rendering the notebook from MD?

**Comment by dmcmurchy** [comment]
Yeah, I'm usually copying the output elsewhere, sometimes into another file or just a different spot in the same notebook. I find the markdown cleaner than the HTML output especially when looking at the unrendered cell (looks nearly identical to the rendered output). What takes 7 lines in markdown ends up being 69 lines in formatted HTML so I would end up scrolling a lot if just using the HTML output.

**Comment by paultiq** [comment]
Could you check it out? Install from git, it's not built. 

See [formatting_notebooks.](https://github.com/iqmo-org/magic_duckdb/blob/main/notebooks/format_examples.ipynb)

**Comment by dmcmurchy** [comment]
So I ran that on my side, but the output is this but wrapped:
```text
'|   employee_id |   deal_size |\n|--------------:|------------:|\n|           101 |      400000 |\n|           101 |      300000 |\n|           201 |      500000 |\n|           301 |      500000 |\n|           405 |      100000 |\n|           405 |       35000 |\n|             1 |      150000 |\n|             1 |      600000 |\n|             1 |      250000 |\n|             1 |       99000 |'
```

And if I do a print on the output I get the easy to copy paste output. 

```text
|   employee_id |   deal_size |
|--------------:|------------:|
|           101 |      400000 |
|           101 |      300000 |
|           201 |      500000 |
|           301 |      500000 |
|           405 |      100000 |
|           405 |       35000 |
|             1 |      150000 |
|             1 |      600000 |
|             1 |      250000 |
|             1 |       99000 |
```

The desired output is the output from `print`.

![image](https://github.com/iqmo-org/magic_duckdb/assets/5430744/4c4a97b8-cd3b-40fd-a60a-b72077e5c480)

**Comment by paultiq** [comment]
Try the latest commit plz: in this version, an IPython.display.Markdown object is returned. ipython then renders it properly, but instead of a string, it returns a Markdown object... so use the `a.data` property

**Comment by paultiq** [comment]
Hmm, not sure I like this version... ipython is rendering the markdown into HTML. Let me know what you think.

**Comment by dmcmurchy** [comment]
I actually like it!  It threw me off at first when I saw it, but the output copies correctly. 
![image](https://github.com/iqmo-org/magic_duckdb/assets/5430744/2fc6471a-778a-4a7d-b19c-7c20d80b3faf)

**Comment by paultiq** [comment]
Nice, thanks! 

Just to document the alternative, instead, could render the str using HTML wrapped in a `<pre/>`:
```                    
mdd = HTML(f"<pre>{md}</pre>")
```

The result would render as: 
![image](https://github.com/iqmo-org/magic_duckdb/assets/104510378/fe3a9ace-e0f8-4600-8990-0110c6b5955a)
