### ISSUE TITLE
Autocomplete in Jupyter

### ISSUE THREAD

**Issue by dominijk** [iqmo-org/magic_duckdb#22]
Many thanks for all your work on this. I was reading the docs I wanted to confirm the expected behaviour of autocompelte in VS Code notebook. I think with `%dql select * from` i should get a list of dataframes or database objects? For me this doesn't happen and i'm trying to debug if that's linked to other VS Code plugs that autocomplete (Tabnine etc.)

**Comment by paultiq** [comment]
It autocompletes from the first letter, so:

![image](https://github.com/iqmo-org/magic_duckdb/assets/104510378/9e75aabd-7e15-4e03-9912-f2800950b22d)

This is my vscode. 

I use it more for column completion: 
![image](https://github.com/iqmo-org/magic_duckdb/assets/104510378/1c85ba03-2595-4c1a-a1fb-7892ae31375a)

**Comment by dominijk** [comment]
thanks for the reply, i think it must be another plugin disrupting the autocompelte. i'll try removing them and see if that solves the issue

**Comment by paultiq** [comment]
Ah. The autocomplete really is based on the table names... I had thought about trying to fully parse the queries or using https://duckdb.org/docs/extensions/autocomplete.html. 

I might revisit, but getting autocomplete to work in ipython in the first place was quite the ordeal.
