### ISSUE TITLE
Pass Current Frame

### ISSUE THREAD

**Issue by paultiq** [iqmo-org/magic_duckdb#26]
Due to https://www.github.com/duckdb/duckdb/pull/12425, only the current frame is inspected. 

We *could* use https://www.github.com/duckdb/duckdb/pull/13896 to scan all frames... but instead, we'll try to pass only the caller frame so that the magic works consistently.

**Comment by dmcmurchy** [comment]
**TLDR:** `%dql set python_scan_all_frames = True;` Is needed to find dataframes ouf of scope.  

Elaborating on the above and providing a workaround as I suspect someone else using magic_duckdb and DuckDB 1.1.1 will run into the same issue.

### Example
_Code Cell_  
```code
%xmode minimal
%reload_ext magic_duckdb
import pandas as pd
df = pd.DataFrame({'test': [1,2]})
%dql SELECT * FROM df;
```

**Generates exception**
```shell
CatalogException: Catalog Error: Table with name df does not exist!
Did you mean "pg_depend"?
LINE 1: FROM df;
             ^

The above exception was the direct cause of the following exception:
ValueError: Error executing FROM df; in DuckDB
```

### Workaround
_Code Cell_  
```code
%xmode minimal
%reload_ext magic_duckdb
%dql set python_scan_all_frames = True; 
import pandas as pd
df = pd.DataFrame({'test': [1,2]})
%dql SELECT * FROM df;
```

**Result**
| | test | 
-- | -- |
0 | 1 |
1| 2|

**Comment by paultiq** [comment]
Thank you, this is great. Will add to readme. 

I was experimenting with passing the locals from the cell into the cell magic, by inspecting 3 frames up the call stack. This is fragile, and requires modifying the locals() before calling duckdb(), so isn't great. 

Separately, I opened a discussion here:  https://github.com/duckdb/duckdb/discussions/14119
