### ISSUE TITLE
How to enable syntax highlighting?

### ISSUE THREAD

**Issue by samsaara** [iqmo-org/magic_duckdb#27]
Hello, thanks for the great lib. I was wondering whether syntax highlighting is available and if so how can it be enabled in jupyter notebook?

![image](https://github.com/user-attachments/assets/62a0f3ff-a483-434b-8d59-ba30db0d7f45)

**Comment by dmcmurchy** [comment]
If you're using VSCcode you can change the code cell to MS SQL which will then highlight all the keywords.

**Comment by paultiq** [comment]
Besides changing the cell type to "MS SQL" works (bottom right of cell) or whatever LSP is installed: 

I could also add an option to register the magic as %SQL instead of %DQL. With this, the SQL LSP would be activated automatically. 

I'll take a look at doing this.

**Comment by paultiq** [comment]
Added example and ability to change to %%sql. This would automatically enable SQL syntax highlighting.

**Comment by samsaara** [comment]
Thanks so much for the quick implementation! <3

**Comment by stannnman** [comment]
> Added example and ability to change to %%sql. This would automatically enable SQL syntax highlighting.

Just to clarify, would this mean using `%%sql `and `%dql` - is there a way to enable "sql" and syntax highlighting for both % and %% ?

**Comment by dmcmurchy** [comment]
@paultiq - Not sure this update to magic_duckdb ever got pushed to pypi as it's not working with 0.1.27

**Comment by paultiq** [comment]
Thank you for pointing this out, I definitely neglected to push it!

I just pushed a pre-release https://pypi.org/project/magic-duckdb/0.1.28b1/ , and will test that, then push the release in a few days.

`pip install magic_duckdb --upgrade --pre` to grab it.

Any feedback welcome!

**Comment by paultiq** [comment]
See "## Modifying the MAGIC NAME from DQL to SQL" in readme

**Comment by dmcmurchy** [comment]
An alternative to using MAGIC NAME is to use [ipython alias_magic](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-alias_magic)

**Example:**
`%alias_magic sql dql`

```
Created `%sql` as an alias for `%dql`.
Created `%%sql` as an alias for `%%dql`.
```

**Comment by paultiq** [comment]
Oh, nice one, thanks!
