### ISSUE TITLE
[Feature]: Add expression template expansion to queries

### ISSUE THREAD

**Issue by ned2** [iqmo-org/magic_duckdb#4]
Would be great to see magic_duckdb get parameterised template expansion, for referencing existing variables in the notebook kernel's top level namespace within SQL queries. 

JupySQL [recently switched](https://github.com/ploomber/jupysql/blob/master/CHANGELOG.md#061-2023-03-02) from using ipython-sql parameters `${expression}` and `{expression}` to `{{expression}}`. The `${expr}` format clashed with DuckDB's use of `$` for prepared statements, but I'm not sure what the motivation was to use `{{}}` over `{}`. 

Personally I would find using single braces convenient for swapping between a magic SQL cell and copying into a Python f-string, whereas double braces is a literal brace in Python f-strings. So using double braces in the SQL magic requires inverting this formatting when going from raw SQL to a Python f-string. But maybe there are some principled reasons for not using `{}`.

For parameter expansion, it looks like JupySQL previously used IPython's [`InteractiveShell.var_expand`](https://github.com/ipython/ipython/blob/main/IPython/core/interactiveshell.py#L3662) and is now using jinja2's [`Template`](https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Template)

**Comment by paultiq** [comment]
Thx! I did add a --replace option recently which does parts of this. It format()'s the line/cell using the shell.user_ns. It does not eval() the text: it's not an actual f-string, and it doesn't pass it via a parameter. 

* It's disabled by default, and isn't friendly if you're using JSON or anything else with {'s

Right now, magic_duckdb can do this: 
```
# Cell 1
%load_ext magic_duckdb
mytable = "foo"
c = 10
```
```
%%dql --replace
create table {mytable} as select * from range({c});
select * from {mytable}
```

Is this what you're looking for? I'm going to think a bit about what you wrote too, the double {{}} format might help solve some JSON issues, and I'm curious about whether the jinja Templates might be more flexible.

**Comment by paultiq** [comment]
I guess two ideas here:
1. We could support query parameterization, rather than string replacement, maybe something like:

```
tablename = "data"
columnname = "start_date"
```
```
%%dql -p tablename columnname

select ? from ?
```

This is pretty simple, but not everything can be parameterized like this. 

2. For string replacement / query string parameterization, I need to think more about this, so ideas are welcome! The current solution + adding ? parameters covers a lot of cases, but not every.

**Comment by ned2** [comment]
Oh cool, the --replace feature is neat. That's partway there, but I very quickly ran into a reason why `{}` doesn't work, which is when you specify a schema, eg for `read_ndjson()` with the `columns={<schema>}` param. so it turns out I can't use that for some of my queries. 

it would also be great to have support for Python expressions and not just be limited to slot filling of variables from the current namespace. so I guess I'm starting to see why Jinja templates could be a good option.

**Comment by ned2** [comment]
Just learned that the Noteable cloud notebook service can use DuckDB for running SQL queries, and they also use `{{expression}}` syntax for templating queries: https://youtu.be/o3KvvhPkaBM

**Comment by paultiq** [comment]
Thank you very much for the suggestions, this is great stuff.

I implemented a first pass at --jinja2 (templated SQL / expansion of {{var}}'s and other jinja2 features) and --params (passing ? params natively to duckdb).

They're in pre-release / v0.1.26b1: %pip install magic_duckdb --pre --upgrade

Removed: 
- --replace: This wasn't very useful with the collisions with JSON

New options: 
- --jinja2
```
table1 = "mytableisawesome"
%dql -t df --jinja create or replace table {{table1}} as select * from range(100)
%dql select * from mytableisawesome
```
- --params
```
obj1 = [1,2,3]
r1 = %dql -p obj select ?
display(r1)

obj1 = [1,2,3]
r2 = %dql -p obj select 2 in (select unnest(?))
display(r2)

# Passing two parameters
obj1 = [1,2,3]
obj2 = "b"
r3 = %dql -p obj -p obj2 select 2 in (select unnest(?)), 'abc' = ?
display(r3)

# Passing two parameters plus jinja template
obj1 = [1,2,3]
obj2 = "b"
obj3 = "this will be passed through jinja2 template"
r4 = %dql -p obj -p obj2 --jinja2 select 2 in (select unnest(?)), 'abc' = ?, '{{obj3}}'
display(r4)
```

**Comment by paultiq** [comment]
Ok, let me think about that / overall config. It's already doing that for types: `%iql -t arrow` means that everything afterwards will default to arrow. 

For Jinja, that also makes sense, but I want to test with more queries to see if there's a downside: whether it's likely to break otherwise good SQL. 

Generally, I think the goal is something like: adding an explicit config option with sensible defaults.

**Comment by ned2** [comment]
the mental model that I'm thinking about is: there's a set of config parameters that have global state (eg output-format, template_expansion=jinja/param/none). they start with a sensible default, and folks can:
1. set the value with a `%` command at the top of their notebook or in a personal config init
2. override it for specific `%dql` etc invocations (but not change the global value of that param)

having eg `%iql -t arrow` modify the global state of a config feels to me like it breaks the principal of least surprise, and require the user to reason about that state at different points in the notebook conditioned on what's been run before

**Comment by paultiq** [comment]
> having eg %iql -t arrow modify the global state of a config feels to me like it breaks the principal of least surprise, and require the user to reason about that state at different points in the notebook conditioned on what's been run before

Agree, and good ideas. I'll split this to a different issue, and close this one out, unless you think there's more needed on the templating part?

**Comment by ned2** [comment]
yeah I think that makes sense. can't think of anything else to add with the templating for now. good to get it in. then move the other concerns to a separate issue about config params.
