### ISSUE TITLE
please update jupysql benchmark

### ISSUE THREAD

**Issue by edublancas** [iqmo-org/magic_duckdb#6]
Hi!

JupySQL maintainer here. I'm really glad I found this project because I was unaware of our performance issues. In JupySQL [0.7.5](https://github.com/ploomber/jupysql/blob/master/CHANGELOG.md#075-2023-05-24), we fixed the performance when using autopandas. You can see a benchmark [here.](https://github.com/ploomber/jupysql/blob/master/benchmarks/duckdb.ipynb)

I'd appreciate if you can update the benchmarks in the README!

Happy to submit a PR but I thought you might want to run them yourself.

**Comment by paultiq** [comment]
Thanks for feedback. It does appear significantly improved for large N. 

Here are the results from last test run (just committed the updated test to match this output). Will update readme this week, unless you have some further feedback.

| |	name |	1|	1000|	1000000| description|
| --- | --- | ---: | ---: | ---:| --- |
|0|	test_magicddb_pandas|	3.47|	4.11|	291.0| %dql -t df query|
|1|	test_duckdb_execute_df|	3.80|	3.39|	281.0| con.execute(query).df() |
|2|	test_duckdb_execute_arrow|	3.91|	4.04|	128.0|  con.execute(query).arrow() |
|3|	test_magicddb_arrow|	4.10|	5.38|	127.0| %dql -t arrow query |
|4|	test_duckdb_sql_df|	6.93|	7.94|	318.0|  con.sql(query).df() |
|5|	test_jupysql|	321.00|	256.00|	547.0|  %config SqlMagic.autopandas = True <br/> %sql query|

**Comment by edublancas** [comment]
thanks for updating the benchmarks! @paultiq - we're working on more performance improvements

**Comment by paultiq** [comment]
Sounds good, one suggestion is to look into how frequently connections are being made. I thought I saw a new connection being created for every query: this doesn't occur when you use a default connection, but it does when you use :memory: or a file.db
